import type { CatalogKind } from "./types";
type SeedItem = {
  kind: CatalogKind;
  name: string;
  description: string;
  data: Record<string, any>;
};
const exercise = (
  name: string,
  slug: string,
  muscle: string,
  equipment: string[],
  cues: string[],
  camera: string,
): SeedItem => ({
  kind: "exercises",
  name,
  description: cues[0],
  data: {
    slug,
    muscle,
    equipment,
    level: "beginner",
    cues,
    camera,
    sets: 3,
    reps: slug === "plank" ? 30 : 10,
  },
});
const meal = (
  name: string,
  slot: string,
  diet: string,
  cuisine: string,
  kcal: number,
  protein: number,
  carbs: number,
  fat: number,
  allergens: string[],
  ingredients: [string, number][],
  instructions: string,
): SeedItem => ({
  kind: "meals",
  name,
  description: `${cuisine} · ${diet} · ${slot.toLowerCase()}`,
  data: {
    slot,
    diet,
    cuisine,
    calories: kcal,
    protein,
    carbs,
    fat,
    allergens,
    ingredients: ingredients.map(([name, grams]) => ({ name, grams })),
    instructions,
    source: "Curated recipe estimates; cooked/edible weights unless stated",
  },
});
export const CATALOG: SeedItem[] = [
  exercise(
    "Bodyweight squat",
    "squat",
    "Legs",
    ["bodyweight"],
    [
      "Sit back with your whole foot grounded.",
      "Keep knees following the direction of your toes.",
      "Lower only as far as you can control without pain.",
    ],
    "Side view, whole body in frame",
  ),
  exercise(
    "Push-up",
    "pushup",
    "Chest & core",
    ["bodyweight"],
    [
      "Keep your shoulders, hips and ankles in one line.",
      "Lower your chest between your hands.",
      "Use an incline if a floor push-up is too demanding.",
    ],
    "Side view, camera around hip height",
  ),
  exercise(
    "Bicep curl",
    "curl",
    "Arms",
    ["dumbbells"],
    [
      "Keep elbows close to your sides.",
      "Lift without swinging your torso.",
      "Lower the weight under control.",
    ],
    "Side view, shoulder, elbow and wrist visible",
  ),
  exercise(
    "Shoulder press",
    "press",
    "Shoulders",
    ["dumbbells"],
    [
      "Brace your trunk and press smoothly overhead.",
      "Keep wrists over elbows.",
      "Stop before you arch your back.",
    ],
    "Side view, hands visible above your head",
  ),
  exercise(
    "Stationary lunge",
    "lunge",
    "Legs & balance",
    ["bodyweight"],
    [
      "Use a stable split stance and lower vertically.",
      "Keep your front knee tracking over your foot.",
      "Complete each side separately.",
    ],
    "Side view, front leg nearest the camera",
  ),
  exercise(
    "Forearm plank",
    "plank",
    "Core",
    ["bodyweight"],
    [
      "Keep shoulders, hips and ankles aligned.",
      "Breathe steadily without holding your breath.",
      "Stop when you cannot keep control.",
    ],
    "Side view, shoulder, hip and ankle visible",
  ),
  {
    kind: "plans",
    name: "Build your foundation",
    description:
      "Three balanced sessions to develop strength and a training rhythm.",
    data: {
      goals: ["fitness", "strength"],
      level: "beginner",
      equipment: ["bodyweight"],
      days: 3,
      minutes: 25,
      exercises: ["squat", "pushup", "lunge", "plank"],
      sets: 3,
      reps: 10,
    },
  },
  {
    kind: "plans",
    name: "Stronger every week",
    description:
      "A progressive dumbbell routine with controlled, repeatable movements.",
    data: {
      goals: ["muscle", "strength"],
      level: "intermediate",
      equipment: ["bodyweight", "dumbbells"],
      days: 4,
      minutes: 40,
      exercises: ["squat", "curl", "press", "pushup"],
      sets: 3,
      reps: 12,
    },
  },
  {
    kind: "plans",
    name: "Move & recharge",
    description: "Short full-body sessions that fit a busy week.",
    data: {
      goals: ["fitness", "fat_loss"],
      level: "all",
      equipment: ["bodyweight"],
      days: 3,
      minutes: 20,
      exercises: ["squat", "lunge", "plank"],
      sets: 2,
      reps: 10,
    },
  },
  {
    kind: "plans",
    name: "Dumbbell essentials",
    description:
      "Learn six fundamental patterns with time to recover between sessions.",
    data: {
      goals: ["muscle", "fitness", "strength"],
      level: "beginner",
      equipment: ["dumbbells", "bodyweight"],
      days: 3,
      minutes: 30,
      exercises: ["squat", "curl", "press", "plank"],
      sets: 3,
      reps: 8,
    },
  },
  meal(
    "Moong chilla & curd",
    "Breakfast",
    "vegetarian",
    "Indian",
    440,
    26,
    56,
    12,
    ["Milk"],
    [
      ["Moong dal (dry)", 80],
      ["Plain curd", 150],
      ["Tomato", 50],
      ["Onion", 40],
      ["Olive oil", 5],
    ],
    "Soak and blend the dal. Mix in chopped vegetables. Cook thin pancakes with the oil and serve with curd.",
  ),
  meal(
    "Chickpea breakfast bowl",
    "Breakfast",
    "vegan",
    "Indian",
    420,
    20,
    62,
    10,
    [],
    [
      ["Cooked chickpeas", 200],
      ["Tomato", 80],
      ["Cucumber", 80],
      ["Lemon", 20],
      ["Olive oil", 5],
    ],
    "Rinse the cooked chickpeas, chop vegetables and toss with lemon and oil.",
  ),
  meal(
    "Overnight oats & yoghurt",
    "Breakfast",
    "vegetarian",
    "Mediterranean",
    430,
    25,
    57,
    12,
    ["Milk"],
    [
      ["Oats (dry)", 60],
      ["Greek yoghurt", 170],
      ["Banana", 90],
      ["Chia seeds", 10],
    ],
    "Combine oats and yoghurt with a little water. Refrigerate overnight. Add banana and chia before serving.",
  ),
  meal(
    "Tofu scramble toast",
    "Breakfast",
    "vegan",
    "Mediterranean",
    460,
    30,
    45,
    18,
    ["Soy", "Wheat"],
    [
      ["Firm tofu", 200],
      ["Whole wheat bread", 70],
      ["Spinach", 50],
      ["Olive oil", 5],
    ],
    "Crumble tofu and cook with spinach and oil. Season lightly and serve on toast.",
  ),
  meal(
    "Rajma rice bowl",
    "Lunch",
    "vegan",
    "Indian",
    560,
    23,
    91,
    11,
    [],
    [
      ["Cooked kidney beans", 200],
      ["Cooked rice", 160],
      ["Tomato", 100],
      ["Onion", 50],
      ["Olive oil", 7],
    ],
    "Cook onion and tomato in oil, add fully cooked kidney beans and simmer. Serve with rice. Never eat raw or undercooked kidney beans.",
  ),
  meal(
    "Paneer tikka grain bowl",
    "Lunch",
    "vegetarian",
    "Indian",
    590,
    35,
    55,
    26,
    ["Milk"],
    [
      ["Paneer", 130],
      ["Cooked brown rice", 150],
      ["Bell pepper", 100],
      ["Plain curd", 50],
    ],
    "Marinate paneer and pepper in curd and spices. Bake until hot and lightly browned. Serve with brown rice.",
  ),
  meal(
    "Chicken & quinoa bowl",
    "Lunch",
    "omnivore",
    "Mediterranean",
    550,
    44,
    54,
    16,
    [],
    [
      ["Cooked chicken breast", 130],
      ["Cooked quinoa", 170],
      ["Cucumber", 100],
      ["Tomato", 80],
      ["Olive oil", 7],
    ],
    "Cook chicken thoroughly to a safe internal temperature, slice and combine with cooked quinoa and vegetables.",
  ),
  meal(
    "Lentil & quinoa salad",
    "Lunch",
    "vegan",
    "Mediterranean",
    520,
    27,
    77,
    12,
    [],
    [
      ["Cooked lentils", 200],
      ["Cooked quinoa", 150],
      ["Cucumber", 100],
      ["Lemon", 20],
      ["Olive oil", 7],
    ],
    "Mix cooked lentils and quinoa with chopped cucumber, lemon and oil. Chill or serve warm.",
  ),
  meal(
    "Soya keema & rice",
    "Dinner",
    "vegan",
    "Indian",
    550,
    37,
    77,
    10,
    ["Soy"],
    [
      ["Soya chunks (dry)", 60],
      ["Cooked rice", 180],
      ["Tomato", 100],
      ["Onion", 60],
      ["Olive oil", 7],
    ],
    "Boil and drain the soya chunks. Chop, simmer in an onion-tomato sauce and serve over rice.",
  ),
  meal(
    "Dal, rice & vegetables",
    "Dinner",
    "vegan",
    "Indian",
    540,
    24,
    88,
    10,
    [],
    [
      ["Cooked lentils", 230],
      ["Cooked rice", 150],
      ["Carrot", 100],
      ["Spinach", 80],
      ["Olive oil", 7],
    ],
    "Simmer lentils with mild seasoning. Steam vegetables and serve alongside rice.",
  ),
  meal(
    "Roast vegetables & white beans",
    "Dinner",
    "vegan",
    "Mediterranean",
    520,
    25,
    75,
    15,
    [],
    [
      ["Cooked white beans", 230],
      ["Potato", 150],
      ["Carrot", 100],
      ["Olive oil", 10],
    ],
    "Roast chopped potato and carrot until tender. Add cooked beans and warm through.",
  ),
  meal(
    "Fish, potatoes & greens",
    "Dinner",
    "omnivore",
    "Mediterranean",
    510,
    38,
    48,
    18,
    ["Fish"],
    [
      ["Cooked salmon", 150],
      ["Potato", 200],
      ["Spinach", 100],
    ],
    "Bake fish until safely cooked. Serve with boiled potatoes and wilted spinach.",
  ),
  meal(
    "Fruit & roasted chana",
    "Snack",
    "vegan",
    "Indian",
    240,
    11,
    42,
    4,
    [],
    [
      ["Roasted chana", 45],
      ["Apple", 130],
    ],
    "Serve the roasted chana with sliced apple. Check packaged chana for allergen cross-contact.",
  ),
  meal(
    "Yoghurt & berries",
    "Snack",
    "vegetarian",
    "Mediterranean",
    220,
    20,
    28,
    4,
    ["Milk"],
    [
      ["Greek yoghurt", 200],
      ["Berries", 100],
    ],
    "Spoon the yoghurt into a bowl and top with washed berries.",
  ),
  {
    kind: "challenges",
    name: "The consistency club",
    description: "Complete 3 training sessions in the last 7 days.",
    data: {
      target: 3,
      days: 7,
      metric: "sessions",
      reward: "Consistency badge",
    },
  },
  {
    kind: "challenges",
    name: "An hour for yourself",
    description: "Accumulate 60 minutes of training in the last 7 days.",
    data: { target: 60, days: 7, metric: "minutes", reward: "Movement badge" },
  },
  {
    kind: "challenges",
    name: "Find your form",
    description: "Record 5 camera sessions in the last 30 days.",
    data: {
      target: 5,
      days: 30,
      metric: "camera",
      reward: "Form explorer badge",
    },
  },
  {
    kind: "gyms",
    name: "Riverfront Strength Studio",
    description:
      "Illustrative listing for testing distance and equipment filters. Not a verified business.",
    data: {
      address: "Demo listing · Nashik",
      lat: 20.0059,
      lng: 73.7793,
      equipment: ["dumbbells", "bodyweight"],
      price: 1500,
      demo: true,
    },
  },
  {
    kind: "gyms",
    name: "City Movement Club",
    description:
      "Illustrative full-service fitness space. Not a verified business.",
    data: {
      address: "Demo listing · Nashik",
      lat: 19.986,
      lng: 73.79,
      equipment: ["dumbbells", "barbell", "bodyweight"],
      price: 2200,
      demo: true,
    },
  },
  {
    kind: "gyms",
    name: "Campus Fitness Collective",
    description:
      "Illustrative bodyweight-focused community space. Not a verified business.",
    data: {
      address: "Demo listing · Nashik",
      lat: 20.027,
      lng: 73.758,
      equipment: ["bodyweight"],
      price: 800,
      demo: true,
    },
  },
  {
    kind: "content",
    name: "Small sessions count",
    description:
      "A manageable session that you repeat is more useful than a perfect plan you cannot sustain.",
    data: { category: "motivation" },
  },
  {
    kind: "content",
    name: "Recovery is part of training",
    description:
      "Give the same muscle groups time to recover. Stop if you feel sharp pain, dizziness or chest discomfort.",
    data: { category: "recovery" },
  },
];
